# Generated by Django 5.0.4 on 2024-07-02 18:07

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default=datetime.datetime(2024, 7, 2, 18, 7, 30, 874475, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
    ]
