# Generated by Django 5.0.4 on 2024-07-02 20:12
import random
from django.db import migrations


class Migration(migrations.Migration):
    def add_barcode(apps, schema_editor):
        Product = apps.get_model('main_app', 'Product')
        all_products = Product.objects.all()
        barcodes = random.sample(range(100_000_000, 1000_000_000), len(all_products))
        for product, barcode in zip(all_products, barcodes):
            product.barcode = barcode
            product.save()

    def reverse_barcodes(apps, schema_editor):
        Product = apps.get_model('main_app', 'Products')
        for product in Product.objects.all():
            product.barcode = 0
            product.save()
    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_barcodes)
    ]
